energy_generator:
  name: 'Fuel'
  value: 0.865

cpu:
  name: 'Xeon'
  speed: '2.2GHZ'
  value: 0.061

variance:
  step_size: 0.5
  threshold: 0.2

thresholds:
  shap_significance: 0.05
  ece_threshold: 0.5

attacks:
  learning_rate: 1e-1
  max_iter: 20
  nb_parallel: 5
  min_num_bins: 5
  min_number_instances: 100
  num_bins_percentage: 0.05



