energy_generator:
  name: 'Fuel'
  value: 0.865

cpu:
  name: 'Xeon'
  speed: '2.2GHZ'
  value: 0.061

variance:
  step_size: 0.5
  threshold: 0.2

thresholds:
  shap_significance: 0.05
  ece_threshold: 0.5


